In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../data/raw/Train.csv")
df.head()

                                                text  label
0  I grew up (b. 1965) watching and loving the Th...      0
1  When I put this movie in my DVD player, and sa...      0
2  Why do people who do not know what a particula...      0
3  Even though I have great interest in Biblical ...      0
4  Im a die hard Dads Army fan and nothing will e...      1

In [3]:
df.shape

(40000, 2)

**Preprocessing**

In [4]:
#Lowercase:

In [5]:
df["text"] = df["text"].str.lower()

In [6]:
df.head()

                                                text  label
0  i grew up (b. 1965) watching and loving the th...      0
1  when i put this movie in my dvd player, and sa...      0
2  why do people who do not know what a particula...      0
3  even though i have great interest in biblical ...      0
4  im a die hard dads army fan and nothing will e...      1

In [7]:
#Remove Punctuation:
import string
exclude = string.punctuation

def remove_punct(text):
    return text.translate(str.maketrans(" ", " ", exclude))


df["text"] = df["text"].apply(remove_punct)

In [8]:
df.head()

                                                text  label
0  i grew up b 1965 watching and loving the thund...      0
1  when i put this movie in my dvd player and sat...      0
2  why do people who do not know what a particula...      0
3  even though i have great interest in biblical ...      0
4  im a die hard dads army fan and nothing will e...      1

**Stopwords Removal:**

In [9]:
import nltk
from nltk.corpus import stopwords

#set stopwords:
stop_words = set(stopwords.words('english'))

#function:
def remove_stopwords(text):
    words = text.split() #tokenization
    filtered = [word for word in words if word not in stop_words]
    return " ".join(filtered)

In [10]:
#apply:
df["text"] = df["text"].apply(remove_stopwords)

In [11]:
df.head()

                                                text  label
0  grew b 1965 watching loving thunderbirds mates...      0
1  put movie dvd player sat coke chips expectatio...      0
2  people know particular time past like feel nee...      0
3  even though great interest biblical movies bor...      0
4  im die hard dads army fan nothing ever change ...      1

**Lemmatization:**

In [15]:
import nltk
from nltk.stem import WordNetLemmatizer

nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Ali\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [16]:
lemmatizer = WordNetLemmatizer()

def lemmatize_text(text):
    words = text.split()
    return " ".join([lemmatizer.lemmatize(word) for word in words])

df["text"] = df["text"].apply(lemmatize_text)

In [17]:
df.head()

                                                text  label
0  grow b 1965 watch love thunderbird mate school...      0
1  movie dvd player sit coke chip expectation hop...      0
2  people know particular time past like feel nee...      0
3  great interest biblical movie bore death minut...      0
4  m die hard dad army fan change get tape dvd au...      1

In [18]:
df.to_csv("../data/processed/cleaned_data.csv", index=False)